version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"
  composer-repository-packages-webstack-nl:
    type: composer-repository
    url: https://packages.webstack.nl
    username: dependabot
    password: "${{secrets.COMPOSER_REPOSITORY_PACKAGES_WEBSTACK_NL_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  registries:
  - composer-repository-packages-webstack-nl
  - git-github-com
